### PR TITLE
Public folder js

### PR DESCRIPTION
**Pull request by AHFotis**
api.js now contains a different type of call and a blueprint for the backend route needed to render returns to handlebars.

### CODE REVIEW

**Review by kdkleven — CHANGES_REQUESTED** [review]
Is there a reason we’re waiting to store the api key in .env?

**Comment by AHFotis** [comment]
> Is there a reason we’re waiting to store the api key in .env?

> Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.

**Comment by kdkleven** [comment]
> > Is there a reason we’re waiting to store the api key in .env?
> 
> > Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.



> > Is there a reason we’re waiting to store the api key in .env?
> 
> > Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.

We should get the api keys off of our repo and store them as configuration variables on heroku.

**Comment by AHFotis** [comment]
> > > Is there a reason we’re waiting to store the api key in .env?
> > 
> > 
> > > Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.
> 
> > > Is there a reason we’re waiting to store the api key in .env?
> > 
> > 
> > > Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.
> 
> We should get the api keys off of our repo and store them as configuration variables on heroku.



> > > Is there a reason we’re waiting to store the api key in .env?
> > 
> > 
> > > Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.
> 
> > > Is there a reason we’re waiting to store the api key in .env?
> > 
> > 
> > > Because technically it's a private key and should be stored in the backend so it can't be retrieved and used on the client side.
> 
> We should get the api keys off of our repo and store them as configuration variables on heroku.

Agreed. I'll approve your changes and save the test function in my notes in case we need to run it again for the keys that return in the object.

**Comment by AHFotis** [comment]
Going back to make changes.

**Pull request closed without merging**
